/**
 * Types shared between the Node build pipeline (tools/) and the browser runtime
 * (src/). The build pipeline emits a `ContentIndex` as a virtual module; the app
 * consumes it. Keeping these in one place guarantees the two halves stay in sync.
 */

export type CardType = 'normal' | 'introduction' | 'conclusion' | 'imponderable' | 'reflection' | 'lookout' | 'abstract';
export type SidecarKind = 'video' | 'audio' | 'picture' | 'text';

/** Raw frontmatter as authored in each HTML file (validated against the schema). */
export interface ItemFrontmatter {
  title: string;
  date: string;
  topic: string;
  category?: string;
  type?: CardType;
  width?: number;
  font_size?: number;
  sidecars?: SidecarFrontmatter[];
  /** Author name (used on the abstract/cover page). */
  author?: string;
  /** Year of publication (used on the abstract/cover page). */
  year?: number;
  /** Institution and/or faculty name (used on the abstract/cover page). */
  institution?: string;
  /** Short summary or subtitle (used on the abstract/cover page). */
  summary?: string;
}

export interface SidecarFrontmatter {
  filename: string;
  kind: SidecarKind;
  description?: string;
  size?: number;
}

/** A resolved media file with its real, build-time-measured pixel dimensions. */
export interface Sidecar {
  filename: string;
  /** Runtime URL (mediaBaseUrl + filename). Equals the first entry of `sources`. */
  url: string;
  /**
   * Ordered list of web-deliverable encodings of this media, modern first with a
   * universal fallback last (e.g. webm → mp4, or avif → webp → jpg). Populated at
   * build time from the files actually present in the content folder, so the app
   * can emit <source>/<picture> fallbacks without probing the network.
   */
  sources: { url: string; type: string }[];
  kind: SidecarKind;
  description?: string;
  size: number;
  /** Intrinsic pixel width (measured via sharp/ffprobe). Audio/text have none. */
  width?: number;
  height?: number;
  /** Rendered size on the canvas at zoom 1, aspect-ratio preserved. */
  renderWidth: number;
  renderHeight: number;
  /** Position of this sidecar box relative to the item's local origin (0,0). */
  relX: number;
  relY: number;
  /** HTML body content for text sidecars (kind='text'). */
  html?: string;
  /**
   * Video only: a tiny base64 JPEG data URI of a frame at ~10% of the duration,
   * generated by `convert:media` into `<stem>.lqip.txt`. Rendered blurred as the
   * canvas placeholder so an unfocused video shows a real still without mounting
   * a <video> element or fetching the media file. Absent before conversion.
   */
  lqip?: string;
}

/** Axis-aligned rectangle in canvas coordinates. */
export interface Rect {
  x: number;
  y: number;
  width: number;
  height: number;
}

/** Per-view placement of an item. */
export interface Placement {
  /** Bounding rect of the whole item (text card + all sidecars). */
  bounds: Rect;
  /** Whether this item sits above (false) or below (true) the timeline axis. */
  below?: boolean;
}

/** A fully resolved content item ready to render. */
export interface ContentItem {
  id: string;
  /** Source html filename stem (also the media prefix). */
  stem: string;
  title: string;
  /** Epoch milliseconds of the item date. */
  timestamp: number;
  /** Original ISO date string. */
  dateIso: string;
  /** True when the date carries a meaningful time-of-day (not midnight). */
  hasTime: boolean;
  topic: string;
  category?: string;
  type: CardType;
  /** Rendered HTML body (frontmatter stripped). Empty string when media-only. */
  html: string;
  /** Plain-text extraction of the body, used for search + autoplay word count. */
  text: string;
  fontSize: number;
  width: number;
  sidecars: Sidecar[];
  /** Computed size + relative position of the text card (0×0 when no body). */
  textCard: { x: number; y: number; width: number; height: number };
  /** Local footprint (width/height) of the whole grouped item. */
  localSize: { width: number; height: number };
  /** True if this item contains any audio-bearing media (video or audio). */
  hasAudio: boolean;
  /** Author name (abstract/cover page metadata). */
  author?: string;
  /** Year of publication (abstract/cover page metadata). */
  year?: number;
  /** Institution and/or faculty name (abstract/cover page metadata). */
  institution?: string;
  /** Short summary or subtitle (abstract/cover page metadata). */
  summary?: string;
  /** Placement per view, keyed by view mode. */
  layout: {
    timeline: Placement;
    topic: Placement;
    book: Placement;
  };
}

export interface TopicCluster {
  topic: string;
  /** Centre of the cluster in topic-view canvas coordinates. */
  center: { x: number; y: number };
  bounds: Rect;
  itemIds: string[];
}

export interface SearchDoc {
  id: string;
  title: string;
  text: string;
  topic: string;
  category?: string;
}

export interface ContentIndex {
  items: ContentItem[];
  topics: string[];
  clusters: TopicCluster[];
  categories: string[];
  /** Id of the abstract item, if present. */
  abstractId: string | null;
  /** Overall canvas bounds per view (for fit-to-screen + minimap). */
  bounds: {
    timeline: Rect;
    topic: Rect;
    book: Rect;
  };
  /** Fuse search documents. */
  searchDocs: SearchDoc[];
  /** Min / max timestamps across all items. */
  timeRange: { min: number; max: number };
  /** Timeline mapping: worldX = (timestamp - timelineMinTimestamp) * timelineScale. */
  timelineScale: number;
  timelineMinTimestamp: number;
  /**
   * Maps original cache/source filenames to deterministic deploy filenames.
   * Only used at build time for the copy step; stripped at runtime.
   */
  mediaRenameMap?: Record<string, string>;
}
